In [3]:
import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/Users/aasthaprajapati/Desktop/Machine learning csv files/winequality-red.csv')

In [5]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [6]:
df = df[['citric acid', 'density','fixed acidity', ]]

In [7]:
normalised_df = (df - df.min())/(df.max()-df.min())

In [8]:
split_percentage = 0.75
msk = np.random.rand(len(df)) <= split_percentage

In [9]:
train = normalised_df[msk]
test = normalised_df[~msk]

In [10]:
x = train[['citric acid', 'density']].values
y = train[['fixed acidity']].values

In [11]:
x

array([[0.        , 0.56754772],
       [0.        , 0.49412628],
       [0.56      , 0.58223201],
       ...,
       [0.08      , 0.35462555],
       [0.1       , 0.37077827],
       [0.47      , 0.3979442 ]])

In [12]:
x[[1]].shape

(1, 2)

In [21]:
x[1].shape

(2,)

In [13]:
index = np.random.randint(0,x.shape[0]-1)
x_s = x[[index]]
x_s.T

array([[0.46      ],
       [0.45594714]])

In [22]:
def stochastic_gradient_descent(x,y,w,b,learning_rate=0.001,iteration=1900 ):
    cost = []
    for i in range(iteration):
        index = np.random.randint(0,x.shape[0]-1)
        x_s = x[[index]]
        y_s = y[[index]]
       
        y_ = x_s.dot(w) + bias
        r = y_s - y_
    
        w_gradient = (-(1)*x_s.T.dot(r))/(len(y))
        b_gradient = (-(1)*np.sum(r))/(len(y))
    
        w = w - learning_rate*w_gradient
        b = b - learning_rate*b_gradient
    
        cost.append(np.sum((((y_s - y_) ** 2) / (2*len(y)))))
    
    return cost  

In [23]:
w = np.random.rand(2,1)

In [24]:
np.sign(w)

array([[1.],
       [1.]])

In [25]:
x_s

array([[0.46      , 0.45594714]])

In [26]:
bias = np.random.rand()

In [27]:
c = stochastic_gradient_descent(x,y,w,bias,0.01, 8000)

In [ ]:
plt.plot(c)

In [ ]:
c[0:10]

In [ ]:
y_pred = x.dot(w) + bias

In [ ]:
np.abs(y-y_pred).mean()

In [ ]:
plt.scatter(normalised_df['citric acid'],normalised_df['fixed acidity'], color='orange')
plt.plot(x.T[0], x.T[0]*w[0]+bias, color='blue')